# Generated by Django 4.2.18 on 2025-01-20 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='move',
        ),
        migrations.AddField(
            model_name='move',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
            preserve_default=False,
        ),
    ]
