# Generated by Django 4.2.18 on 2025-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.JSONField(default=[[], [], []]),
        ),
    ]
